### PR TITLE
List Component: Adds the ability to navigate on row click

### PR DESCRIPTION
**Pull request by DanielOrmeno**
- Adds the ability to navigate on row click
- Stops click event propagation on EditButton and Delete Button

### CODE REVIEW

**Comment by sgobotta** [comment]
Hello, thanks for the contribution. Please add a reference to the issue.

**Comment by sgobotta** [comment]
You can check which files to fix by running: `npm run lint` locally. The `demo` files shouldn't break the linter.

**Comment by DanielOrmeno** [comment]
Done!

**Comment by sgobotta** [comment]
Thanks you @DanielOrmeno !

Closes #121

**Pull request merged**
