### PR TITLE
add pre-commit lint hook

### PR DESCRIPTION
**Pull request by TheAkshitS**

### CODE REVIEW

**Comment by sgobotta** [comment]
Hello! Thanks for opening this PR. Though, to approve them we need you to briefly comment what you did and assign the issue to yourself.

**Comment by TheAkshitS** [comment]
Hi Santiago, I basically added a pre-commit hook to avoid eslint errors.
https://github.com/Cambalab/vue-admin/issues/158

**Comment by sgobotta** [comment]
> Hi Santiago, I basically added a pre-commit hook to avoid eslint errors.
> #158

Please comment #158, saying that you're already working so that nobody else works in the same task :)

**Comment by sgobotta** [comment]
When #162 is merged (which might be tomorrow) I'll take a look into this one. We probably want to do something with the `prettier eslint configuration`.

**Comment by TheAkshitS** [comment]
> > Hi Santiago, I basically added a pre-commit hook to avoid eslint errors.
> > #158
> 
> Please comment #158, saying that you're already working so that nobody else works in the same task :)
> 
> We still have no PR template but it's always nice to provide instructions telling how to test your new feature.

So right now eslint's recommended rule is being used and there're no rules included, for testing purpose, you can just add in any rule like "semi": ["error", "always"] in the rules array, try to commit any file with lint error/s and the lint errors should be automatically fixed when you commit.

**Comment by sgobotta** [comment]
Closed due to inactivity. No code reusal when we're using prettier as eslint conf.

**Pull request closed without merging**
