### PR TITLE
Feedback on failing authentication

### PR DESCRIPTION
**Pull request by jejoivanic**
## Description

**This PR provides:**
-   A way for the user to handle the error response from the authentication request and display whatever the user wants in case of failure.
-   Unit tests and e2e tests have been implemented.
-   For the default AuthenticationLayout, added snackbar on failing authentication.

Closes https://github.com/Cambalab/vue-admin/issues/180

## Type of change

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [X] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

## How Has This Been Tested?

Apart from running all previous tests (unit/e2e) two different e2e tests were added. Those are
-    Testing snackbar visibility and content on failing authentication for invalid username
-    Testing snackbar visibility and content on failing authentication for invalid password

## Checklist:

-   [X] **I have performed a self-review of my own code**
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [X] **My changes generate no new warnings**
-   [X] I have added tests that prove my fix is effective or that my feature works
-   [X] **New and existing unit tests pass locally with my changes**

### CODE REVIEW

**Comment by jejoivanic** [comment]
**Why is this a WIP?**

I implemented a solution which requires the user to handle the asyn response from the authentication with a `then`. In this `then`'s callback the user receives a parameter which represents the error of the response if any. If not, the layout will change and nothing should be received in this parameter.

```
...
  this.va.login(user, password)
    .then(err => {
      if (err)
        doSomething()
    })
...
```

I've thought about this solution but I don't really know if this is the right approach for this, however I could not find a better way. I've consider passing also the user, to resemble other libraries which, in similar cases, defines a callback like `(data, err) => { ... }`.
That's my only concern about this solution. I'll wait for some comments or feedback.

**Comment by jejoivanic** [comment]
I also modified the response from the demo server to return 401 status when the user or password is incorrect.

**Comment by sgobotta** [comment]
Not really sure what's going on. My guess is that the **snackbar** disappears before Cypress finally finds it in the virtual dom.

**Comment by sgobotta** [comment]
Keeps failing, even with a timeout of `0`. I'm going to temporarily remove those tests.

**Comment by sgobotta** [comment]
End to end tests for `AuthLayout` snackbar were removed in 3326fe18eba3d0d13e124adac5a862495b66223b

**Pull request merged**
