### PR TITLE
Chore/add linting to pre commit hook

### LINKED ISSUE #158: Add a pre-commit hook to avoid eslint errors/warnings
**Is your feature request related to a problem? Please describe.**
#7 enforces developers to write clean code according to prettier eslint rules. It would be nice to have a pre-commit hook that avoids developers committing code with errors or warnings.

**Describe the solution you'd like**
Whenever a developer commits, a pre-commit hook should run the **lint** package.json script. 

> Note that we don't want to automatically fix errors/warnings, **npm run lint** is already configured to do the job.

**Describe alternatives you've considered**
[Lint staged](https://prettier.io/docs/en/precommit.html#option-1-lint-staged-https-githubcom-okonet-lint-staged) seems to be a pretty good and simple solution.

### PR DESCRIPTION
**Pull request by C3-TKO**
## Description

- Added pre commit hook functionality via husky
- Added lint staged to lint all javascript files with the `npm run lint` script prior adding the files to git stage, if lint tests are successful

Closes #158

## Type of change

- [x] CI environment got enhanced - `npm version patch` recommended   

## How Has This Been Tested?

I tried to stage a main.js file with linter violations, e.g. add the following lines somewhere in src/main.js

```javascript
if (foo) return
```

**Expected result:**
Bildschirmfoto 2019-10-20 um 20 53 34

## Checklist:

> The following options in **bold** are required for a PR approval. Please check the boxes only if necessary, it help us minimizing the reviewing process.

-   [x] **I have performed a self-review of my own code**
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [x] **My changes generate no new warnings**
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [x] **New and existing unit tests pass locally with my changes**

### CODE REVIEW

**Comment by sgobotta** [comment]
@C3-TKO Thanks for submitting this PR! I'll review it soon.

Meanwhile I'm changing the target branch, as stated in the [`README.md`](https://github.com/Cambalab/vue-admin#contributing-and-future-features).

**Comment by sgobotta** [comment]
@C3-TKO could you comment in the related issue claiming you're working on it? That way I can assign it to you and you'll appear in the changelog as contributor, thanks!

**Comment by sgobotta** [comment]
@C3-TKO could you add support for `.vue`, `.json` and`.css` files in the `src/` directory?

It should be something like this: `src/**/*.{css,js,json,vue}`

Another thing, I can't get it running in my local project. I followed this steps:

+   Cloned your branch
+   Run `npm install`
+   Write a failing piece of code in `src/main.js`: `if (foo) return`
+   Run `git add src/main.js`
+   Run `git commit -m "a"`
+   No husky hooks appeared

It must be something in my environment but I have no clue why.

Why do we need another script in the `package.json`. Is it not enough with `npm run lint` ?

**Comment by C3-TKO** [comment]
> Why do we need another script in the package.json. Is it not enough with npm run lint ?
I have not added any additional script to the packag.json file. However the git diff view might suggest I did. I just added husky and lint staged as dev dependency and added a lint-staged config to the package.json file

**Comment by C3-TKO** [comment]
> @C3-TKO could you add support for .vue, .json and.css files in the src/ directory?

@sgobotta Should lint for CSS not be preferably done it in a more suitable listing tool than es lint?

I will add support for .vue, .json and .css files tomorrow

**Comment by C3-TKO** [comment]
@sgobotta I will setup my machine (MBPro Mid 2019) with the same node env as the you mentioned and try to install husky and lint-staged agin in order to try to replicate your Report: https://github.com/Cambalab/vue-admin/pull/183#issuecomment-544287172

**Comment by C3-TKO** [comment]
I noticed that there is only one css source file within this project
./src/assets/fonts/Montserrat/Montserrat.css

Do you really need a linter for a downloaded css font file description? ;-)

This project seems to use sass files

**Comment by C3-TKO** [comment]
Imho it is easier to include custom fonts via google fonts loader:

<link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">

**Comment by sgobotta** [comment]
> I noticed that there is only one css source file within this project
> ./src/assets/fonts/Montserrat/Montserrat.css
> 
> Do you really need a linter for a downloaded css font file description? ;-)
> 
> This project seems to use sass files

Oh, yeah, you're absolutely right. Let's keep it to `.json` for config files, `.vue` for components and `.js` for the library files.

> Imho it is easier to include custom fonts via google fonts loader:

That's true. When we did this we didn't want to rely on Google to do that kind of stuff and have them working without internet connection.

**Comment by sgobotta** [comment]
> @sgobotta I will setup my machine (MBPro Mid 2019) with the same node env as the you mentioned and try to install husky and lint-staged agin in order to try to replicate your Report: [#183 (comment)](https://github.com/Cambalab/vue-admin/pull/183#issuecomment-544287172)

I'm not sure what could that bee. Followed a few issue sin husky regarding errors in `node` version above 8.6.0. Tried a few older (< 8.6.0) versions but it didn't work. I'll keep on looking for solutions too.

**Comment by C3-TKO** [comment]
I installed node in version 10.16.0 along with npm in 6.9.0. Pre-commit hooks were running as intended.

Bildschirmfoto 2019-10-21 um 23 37 38

Maybe you could try to run this repo in a node.js docker container.

Ich changed the config to check for js, json and vue files

**Comment by sgobotta** [comment]
It seems it was an issue with my `git` version. Sometimes during `npm install`, `husky` can't find the `.git//hooks` directory and fails to override the hook files header with `#husky <version>`.

Thanks for your contribution @C3-TKO :tada: :)

**Pull request merged**
