### PR TITLE
5 spinner loader on api calls

### PR DESCRIPTION
**Pull request by jejoivanic**
## Feature
Implemented a default spinner component which covers the Vue-Admin Actions views during the requests. For the template I used the Vuetify component v-progress-circular in color green.
## Implementation
Implemented in an isolated component which has a property of type Boolean to indicate whether the spinner should be displayed or not.
For the loading state, interceptors for the request and response were implemented. These interceptors commit an action which sets the isLoading state to true or false.
All the Action components use the same getter for the isLoading state to pass the value to the Spinner component.

### CODE REVIEW

**Comment by sgobotta** [comment]
Nice work on the Spinners!
CI is stopping on some unused vars. Is this WIP or should we just fix and merge?

**Comment by jejoivanic** [comment]
I'm so sorry! It's intended to be a finished work so I will review the code right away!

**Comment by jejoivanic** [comment]
There you go. There were some lint errors in the e2e tests. I needed to create a getter in the spinner-list test to solve a variable scoping problem.

**Comment by sgobotta** [comment]
Great! Merging right away.

**Pull request merged**
