### PR TITLE
Deprecate crud components as arrays

### PR DESCRIPTION
**Pull request by SevenIndirecto**
Hey, with this PR I'm deprecating the option to use crud view components as arrays as per https://github.com/Cambalab/vue-admin/issues/94

Is this acceptable?

### CODE REVIEW

**Comment by sgobotta** [comment]
Nice work, that's what we were expecting.

One little thing, we point all our PRs to the `develop` branch unless it's a hotfix. Could you please fix the conflcits in `route.bindings`? Then we'll be ready to merge.

Thanks!

**Comment by SevenIndirecto** [comment]
Sure thing, sorry about missing the branch details.

**Comment by sgobotta** [comment]
> Sure thing, sorry about missing the branch details.

It's fine, the updated `README.md` with contributing instructions isn't in `master` yet. Thanks for your work!

**Comment by sgobotta** [comment]
Closes #94

**Pull request merged**
