### PR TITLE
7 - configures ESLint to enforce coding style consistency

### PR DESCRIPTION
**Pull request by agustinariq**

### CODE REVIEW

**Comment by agustinariq** [comment]
@sgobotta you were right about the duplicated configuration. I fixed it in the last commit. 

About how to run the linter, I run `npm run lint` in the root of the project and it finds the errors in the cases you mentioned (double quotes). Can you check it again with these new changes, please?

**Comment by sgobotta** [comment]
> @sgobotta you were right about the duplicated configuration. I fixed it in the last commit.
> 
> About how to run the linter, I run `npm run lint` in the root of the project and it finds the errors in the cases you mentioned (double quotes). Can you check it again with these new changes, please?

Alright, I'll be checking it.

**Comment by sgobotta** [comment]
Everything works great! I was editing the wrong file in my tests.

Another thing i wasn't sure to add or not. I'd make the linting a little more restrictive and add a zero tolerance for warnings during lint checks with a a new flag in the `npm run lint` command.
What do you think? Would it help promoting code style consistency?

**Comment by agustinariq** [comment]
> What do you think? Would it help promoting code style consistency?

Sure, totally. I think code consistency should be maximized if it's possible.

 I'll add the flag `--max-warnings 0` to the `npm run lint` command. In this way, ESLint will exit with a successful code only when warnings and errors count to 0.

**Comment by sgobotta** [comment]
Nice work!! :tada: I'll fix conflicts and merge right away

**Pull request merged**
